apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fastapi-demo
  namespace: default
spec:
  targetNamespace: fastapi-demo
  storageNamespace: fastapi-demo
  install:
    createNamespace: true
  values:
     backend:
      service:
        port: 18180
        type: LoadBalancer
      metrics:
        serviceMonitor:
          enabled: true
    frontend:
      service:
        port: 18080
        type: LoadBalancer
      metrics:
        serviceMonitor:
          enabled: true
