apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops
  namespace: flux-system
spec:
  targetNamespace: flux-system
  storageNamespace: flux-system
  values:
    WEAVE_GITOPS_FEATURE_TELEMETRY: "true"
    service:
      type: LoadBalancer
    rbac:
      impersonationResourceNames: ['admin']
    adminUser:
      create: true
      username: admin
      passwordHash: $2a$10$gy4cmsyzi9GYvVKylDWig.mos4YuALjnDxA4Vew/aPmNtP6.FW34O  # echo admin | gitops get bcrypt-hash