apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 51.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: default
      interval: 1m
      TargetNamespace: monitoring
  values: {}