apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 52.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 1m
  values: {}