apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: openelb
  namespace: flux-system
spec:
  values:
    prometheus:
      serviceMonitor:
        enabled: true
      podMonitor:
        enabled: true
    configInline: