apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../base
  - ip-address-pool.yaml
  - l2-advertisement.yaml

patchesStrategicMerge:
  - helm-release.yaml