apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: backstage
spec:
  targetNamespace: backstage
  storageNamespace: backstage
  install:
    createNamespace: true
  values:
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: edge-endpoint
    backstage:
      image:
        tag: 1.20.0
    postgresql:
      primary:
        persistence:
          size: 2Gi
        resources:
          requests:
            cpu: 100m
            memory: 128Mi