apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: backstage
spec:
  targetNamespace: backstage
  storageNamespace: backstage
  install:
    createNamespace: true
  values:
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: edge-endpoint
    backstage:
      image:
        tag: 1.20.0
      appConfig:
        app:
          baseUrl: http://localhost:7007
        backend:
          baseUrl: http://localhost:7007
          cors:
            origin: http://localhost:7007
          auth:
            keys:
              - secret: W4Lxw7m8qErGKjq/6hCS68wlFtZ25HGp  # node -p 'require("crypto").randomBytes(24).toString("base64")'
    postgresql:
      primary:
        persistence:
          size: 2Gi
        resources:
          requests:
            cpu: 100m
            memory: 128Mi