apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: backstage
spec:
  targetNamespace: backstage
  storageNamespace: backstage
  install:
    createNamespace: true
  values:
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: edge-endpoint
    backstage:
      extraEnvVarsSecrets:
        - killercoda-env
      image:
        registry: ghcr.io
        repository: ghcr.io/testruction/backstage/all-in-one
        tag: 1.19.1
      appConfig:
        app:
          baseUrl: ${FRONTEND_URL}
        backend:
          baseUrl: ${BACKEND_URL}
          cors:
            origin: ${FRONTEND_URL}
    postgresql:
      primary:
        persistence:
          size: 2Gi
        resources:
          limits: {}
          requests: {}