apiVersion: v1
kind: Namespace
metadata:
  name: fastapi-demo
  labels:
    istio-injection: enabled
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fastapi-demo
  namespace: flux-system
  labels:
    backstage.io/kubernetes-id: fastapi-demo
spec:
  targetNamespace: fastapi-demo
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./apps/fastapi-demo/localhost
  prune: true
  wait: true
  timeout: 5m
  decryption:
