---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  targetNamespace: istio-system
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/istio/base
  prune: true
  wait: true
  timeout: 5m
