apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: velero
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/velero/localhost
  prune: true
  wait: true
  timeout: 5m