---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: backstage
  namespace: backstage
spec:
  image: ghcr.io/testruction/backstage-tutorial/backage
  interval: 1h
  provider: generic