---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: backstage
spec:
  imageRepositoryRef:
    name: backage
  filterTags:
    pattern: '.*[-rc|-beta|-alpha].*'
  policy:
    semver:
      range: '>=1.0.0'