apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: demo
spec:
  targetNamespace: fastapi-demo
  releaseName: demo
  install:
    createNamespace: true
  values:
    backend:
      service:
        port: 18180
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: edge-endpoint
      metrics:
        serviceMonitor:
          enabled: true
    frontend:
      service:
        port: 18080
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: edge-endpoint
      metrics:
        serviceMonitor:
          enabled: true
