apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kiali
  namespace: flux-system
spec:
  values:
    deployment:
      service_annotations:
        metallb.universe.tf/allow-shared-ip: edge-endpoint
      service_type: LoadBalancer