---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: openelb
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: istio-system
  releaseName: istio
  install:
    createNamespace: true
  chart:
    spec:
      chart: openelb
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: kubesphere
      interval: 1m
  values: {}
