apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backstage
spec:
  targetNamespace: backstage
  storageNamespace: backstage
  install:
    createNamespace: true
  values:
    backstage:
      image:
        registry: ghcr.io
        repository: testruction/backstage
        tag: 1.7.0-alpha1