apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backstage
spec:
  targetNamespace: backstage
  storageNamespace: backstage
  install:
    createNamespace: true
  values:
    backstage:
      extraEnvVarsSecrets:
        - killercoda-env
      image:
        registry: ghcr.io
        repository: testruction/backstage/all-in-one
        tag: 1.7.0
      appConfig:
        app:
          baseUrl: ${FRONTEND_URL}
        backend:
          baseUrl: ${BACKEND_URL}
          cors:
            origin: ${FRONTEND_URL}