---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: backstage
spec:
  image: ghcr.io/testruction/backstage-tutorial/backstage/all-in-one
  interval: 1h
  provider: generic