apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailpit
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: smtp-system
  releaseName: mailpit
  install:
    createNamespace: true
  chart:
    spec:
      chart: mailpit
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: mailpit
      interval: 1m
  values:
    image:
      tag: v1.10.4