apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fastapi-demo
spec:
  interval: 1m
  url: https://github.com/testruction/fastapi-sqlalchemy-cockroachdb
  ref:
    branch: main
  # ignore: |
  #   # exclude all
  #   /*
  #   # include charts directory
  #   !/chart/