apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: demo
spec:
  interval: 5m
  chart:
    spec:
      chart: chart/
      version: 0.2.0
      sourceRef:
        kind: GitRepository
        name: fastapi-demo
      interval: 1m
  values: {}
