---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: backend
spec:
  image: ghcr.io/testruction/fastapi-sqlalchemy-cockroachdb/backend
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: frontend
spec:
  image: ghcr.io/testruction/fastapi-sqlalchemy-cockroachdb/frontend
  interval: 1h
  provider: generic