---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: velero
  releaseName: velero
  install:
    createNamespace: true
  chart:
    spec:
      chart: velero
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
      interval: 1m
  values: {}
